# -*- coding: utf-8 -*-
"""
Türkiye Atık Yönetimi Yönetmeliği atık kodları -> ADR taşıma bilgileri
(UN No, Sınıf, Paketleme Grubu, ADR Sevkiyat Adı) referans listesi.

Kaynak: klncumut6565/sefer_aktarim_bosaltma_kontrol_destekli reposundaki
ATIK_ADR sözlüğü (408 tehlikeli atık kodu). Bu programın kendi ADR Tablo A
dosyasıyla eşleştirilip UN No dört haneye tamamlanmış, PG'si tabloyla
eşleşmeyen kayıtlar Tablo A'daki gerçek (tek anlamlı) PG ile düzeltilmiştir.
Birden fazla olası PG'si olan (yoğunluğa göre değişen) birkaç kayıt kasıtlı
olarak düzeltilmeden bırakılmıştır — bunlar arayüzde 'manuel kontrol
gerekir' olarak işaretlenir.

Bu dosya statiktir; atık kodu listesi değiştiğinde elle güncellenmelidir.
"""

ATIK_KODLARI: dict[str, dict] = {
    "01 03 04*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "01 03 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "01 03 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "01 03 10*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "01 04 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "01 05 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "01 05 06*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "02 01 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "03 01 04*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "03 02 01*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "03 02 02*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "03 02 03*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "03 02 04*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "03 02 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "04 01 03*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "04 02 14*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "04 02 16*": {"un_no": "1263", "sinif": "3", "pg": "II", "sevkiyat_adi": "BOYA (boya, vernik, emaye, renklendirici, lake, cila, parlatıcı, sıvı  dolgu ve sıvı vernik bazı dâhil) veya  BOYA İLE İLGİLİ MALZEME  (boya inceltici veya azaltıcı bileşiği  dâhil) (50 °C'de buhar basıncı 110  kPa’dan daha yüksek olan)"},
    "04 02 19*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "05 01 02*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "05 01 03*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "05 01 04*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "05 01 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "05 01 06*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "05 01 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "05 01 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "05 01 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "05 01 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "05 01 12*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "05 01 15*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "05 06 01*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "05 06 03*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "05 07 01*": {"un_no": "2025", "sinif": "6.1", "pg": "III", "sevkiyat_adi": "CIVA BİLEŞİĞİ, KATI, B.B.B."},
    "06 01 01*": {"un_no": "1830", "sinif": "8", "pg": "II", "sevkiyat_adi": "SÜLFÜRİK ASİT %51'den fazla asit  içeren"},
    "06 01 02*": {"un_no": "1789", "sinif": "8", "pg": "III", "sevkiyat_adi": "HİDROKLORİK ASİT"},
    "06 01 03*": {"un_no": "1790", "sinif": "8", "pg": "III", "sevkiyat_adi": "ADR SINIFLANDI: 8"},
    "06 01 04*": {"un_no": "1805", "sinif": "8", "pg": "III", "sevkiyat_adi": "FOSFORİK ASİT, ÇÖZELTİ"},
    "06 01 05*": {"un_no": "2031", "sinif": "8", "pg": "III", "sevkiyat_adi": "ADR SINIFLANDI: 8"},
    "06 01 06*": {"un_no": "3264", "sinif": "8", "pg": "III", "sevkiyat_adi": "AŞINDIRICI SIVI, ASİDİK, İNORGANİK, B.B.B."},
    "06 02 01*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "06 02 03*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "06 02 04*": {"un_no": "1813", "sinif": "8", "pg": "II", "sevkiyat_adi": "POTASYUM HİDROKSİT, KATI"},
    "06 02 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "06 03 11*": {"un_no": "1588", "sinif": "6.1", "pg": "III", "sevkiyat_adi": "SİYANÜRLER, İNORGANİK, KATI, B.B.B."},
    "06 03 13*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "06 03 15*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "06 04 03*": {"un_no": "1557", "sinif": "6.1", "pg": "III", "sevkiyat_adi": "ARSENİK BİLEŞİĞİ, KATI, B.B.B., inorganik, içeriği: Arsenatlar, b.b.b., Arsenitler, b.b.b. ve Arsenik sülfürler,  b.b.b."},
    "06 04 04*": {"un_no": "2025", "sinif": "6.1", "pg": "III", "sevkiyat_adi": "CIVA BİLEŞİĞİ, KATI, B.B.B."},
    "06 04 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "06 05 02*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "06 06 02*": {"un_no": "1350", "sinif": "4.1", "pg": "III", "sevkiyat_adi": "KÜKÜRT"},
    "06 07 01*": {"un_no": "2212", "sinif": "9", "pg": "II", "sevkiyat_adi": "ASBEST, AMFİBOL (amosit, tremolit, aktinolit, antofilit, krokidolit)"},
    "06 07 02*": {"un_no": "1362", "sinif": "4.2", "pg": "III", "sevkiyat_adi": "KARBON, AKTİF"},
    "06 07 03*": {"un_no": "1564", "sinif": "6.1", "pg": "III", "sevkiyat_adi": "BARYUM BİLEŞİĞİ, B.B.B."},
    "06 07 04*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "06 08 02*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "06 09 03*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "06 10 02*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "06 13 01*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "06 13 02*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "06 13 04*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "06 13 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 01 01*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 01 03*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 01 04*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 01 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 01 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 01 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 01 10*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 01 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 02 01*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 02 03*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 02 04*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 02 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 02 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 02 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 02 10*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 02 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 02 14*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 02 16*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 03 01*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 03 03*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 03 04*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 03 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 03 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 03 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 03 10*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 03 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 04 01*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 04 03*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 04 04*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 04 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 04 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 04 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 04 10*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 04 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 04 13*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 05 01*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 05 03*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 05 04*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 05 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 05 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 05 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 05 10*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 05 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 05 13*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 06 01*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 06 03*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 06 04*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 06 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 06 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 06 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 06 10*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 06 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 07 01*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 07 03*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 07 04*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "07 07 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 07 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 07 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 07 10*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "07 07 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "08 01 11*": {"un_no": "1263", "sinif": "3", "pg": "II", "sevkiyat_adi": "BOYA (boya, vernik, emaye, renklendirici, lake, cila, parlatıcı, sıvı  dolgu ve sıvı vernik bazı dâhil) veya  BOYA İLE İLGİLİ MALZEME  (boya inceltici veya azaltıcı bileşiği  dâhil) (50 °C'de buhar basıncı 110  kPa’dan daha yüksek olan)"},
    "08 01 13*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "08 01 15*": {"un_no": "3175", "sinif": "4.1", "pg": "II", "sevkiyat_adi": "KATILAR veya katı karışımları  (müstahzar ve atıklar gibi), parlama  noktası 60 °C'ye kadar olan  ALEVLENEBİLİR SIVI, B.B.B. İÇEREN"},
    "08 01 17*": {"un_no": "3175", "sinif": "4.1", "pg": "II", "sevkiyat_adi": "KATILAR veya katı karışımları  (müstahzar ve atıklar gibi), parlama  noktası 60 °C'ye kadar olan  ALEVLENEBİLİR SIVI, B.B.B. İÇEREN"},
    "08 01 19*": {"un_no": "1263", "sinif": "3", "pg": "II", "sevkiyat_adi": "BOYA (boya, vernik, emaye, renklendirici, lake, cila, parlatıcı, sıvı  dolgu ve sıvı vernik bazı dâhil) veya  BOYA İLE İLGİLİ MALZEME  (boya inceltici veya azaltıcı bileşiği  dâhil) (50 °C'de buhar basıncı 110  kPa’dan daha yüksek olan)"},
    "08 01 21*": {"un_no": "1263", "sinif": "3", "pg": "II", "sevkiyat_adi": "BOYA (boya, vernik, emaye, renklendirici, lake, cila, parlatıcı, sıvı  dolgu ve sıvı vernik bazı dâhil) veya  BOYA İLE İLGİLİ MALZEME  (boya inceltici veya azaltıcı bileşiği  dâhil) (50 °C'de buhar basıncı 110  kPa’dan daha yüksek olan)"},
    "08 03 12*": {"un_no": "1210", "sinif": "3", "pg": "III", "sevkiyat_adi": "MATBAA MÜREKKEBİ, alevlenebilir veya MATBAA  MÜREKKEBİ İLE İLGİLİ  MALZEME (matbaa mürekkebi  inceltici veya azaltıcı bileşiği dâhil), alevlenebilir"},
    "08 03 14*": {"un_no": "1210", "sinif": "3", "pg": "III", "sevkiyat_adi": "MATBAA MÜREKKEBİ, alevlenebilir veya MATBAA  MÜREKKEBİ İLE İLGİLİ  MALZEME (matbaa mürekkebi  inceltici veya azaltıcı bileşiği dâhil), alevlenebilir"},
    "08 03 16*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "08 03 17*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "08 03 19*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "08 04 09*": {"un_no": "3175", "sinif": "4.1", "pg": "II", "sevkiyat_adi": "KATILAR veya katı karışımları  (müstahzar ve atıklar gibi), parlama  noktası 60 °C'ye kadar olan  ALEVLENEBİLİR SIVI, B.B.B. İÇEREN"},
    "08 04 11*": {"un_no": "3175", "sinif": "4.1", "pg": "II", "sevkiyat_adi": "KATILAR veya katı karışımları  (müstahzar ve atıklar gibi), parlama  noktası 60 °C'ye kadar olan  ALEVLENEBİLİR SIVI, B.B.B. İÇEREN"},
    "08 04 13*": {"un_no": "3175", "sinif": "4.1", "pg": "II", "sevkiyat_adi": "KATILAR veya katı karışımları  (müstahzar ve atıklar gibi), parlama  noktası 60 °C'ye kadar olan  ALEVLENEBİLİR SIVI, B.B.B. İÇEREN"},
    "08 04 15*": {"un_no": "1993", "sinif": "3", "pg": "II", "sevkiyat_adi": "ALEVLENEBİLİR SIVI, B.B.B (50  °C'de buhar basıncı 110 kPa’dan daha  yüksek olan)"},
    "08 04 17*": {"un_no": "1286", "sinif": "3", "pg": "III", "sevkiyat_adi": "ÇAM SAKIZI YAĞI"},
    "08 05 01*": {"un_no": "2206", "sinif": "6.1", "pg": "III", "sevkiyat_adi": "İZOSİYANATLAR, ZEHİRLİ, B.B.B. veya İZOSİYANAT  ÇÖZELTİSİ, ZEHİRLİ, B.B.B."},
    "09 01 01*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "09 01 02*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "09 01 03*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "09 01 04*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "09 01 05*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "09 01 06*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "09 01 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "09 01 13*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "10 01 04*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 01 09*": {"un_no": "2796", "sinif": "8", "pg": "II", "sevkiyat_adi": "SÜLFÜRİK ASİT %51'den az asit  içeren veya AKÜ SUYU, ASİTLİ"},
    "10 01 13*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 01 14*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 01 16*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 01 18*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 01 20*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 01 22*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 02 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 02 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 02 13*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 03 04*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 03 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 03 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 03 15*": {"un_no": "3543", "sinif": "4.3", "pg": "III", "sevkiyat_adi": "NESNELER, SU İLE TEMAS  ETTİĞİNDE ALEVLENEBİLİR GAZLAR AÇIĞA ÇIKARAN  MADDE İÇEREN, B.B.B."},
    "10 03 17*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "10 03 19*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 03 21*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 03 23*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 03 25*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 03 27*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 03 29*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 04 01*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 04 02*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 04 03*": {"un_no": "1573", "sinif": "6.1", "pg": "II", "sevkiyat_adi": "KALSİYUM ARSENAT"},
    "10 04 04*": {"un_no": "1562", "sinif": "6.1", "pg": "II", "sevkiyat_adi": "ARSENİK TOZU"},
    "10 04 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 04 06*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 04 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 04 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 05 03*": {"un_no": "1562", "sinif": "6.1", "pg": "II", "sevkiyat_adi": "ARSENİK TOZU"},
    "10 05 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 05 06*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 05 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 05 10*": {"un_no": "2813", "sinif": "4.3", "pg": "III", "sevkiyat_adi": "SU İLE TEPKİMEYE GİREN, KATI, B.B.B."},
    "10 06 03*": {"un_no": "1562", "sinif": "6.1", "pg": "II", "sevkiyat_adi": "ARSENİK TOZU"},
    "10 06 06*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 06 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 06 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 07 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 08 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 08 10*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 08 12*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 08 15*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 08 17*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 08 19*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 09 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 09 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 09 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 09 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 09 13*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 09 15*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 10 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 10 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 10 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 10 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 10 13*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 10 15*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 11 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 11 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 11 13*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 11 15*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 11 17*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 11 19*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 12 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 12 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 13 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 13 12*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "10 14 01*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "11 01 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "11 01 06*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "11 01 07*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "11 01 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "11 01 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "11 01 11*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "11 01 13*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "11 01 15*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "11 01 16*": {"un_no": "1286", "sinif": "3", "pg": "III", "sevkiyat_adi": "ÇAM SAKIZI YAĞI"},
    "11 01 98*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "11 02 02*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "11 02 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "11 02 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "11 03 01*": {"un_no": "3243", "sinif": "6.1", "pg": "II", "sevkiyat_adi": "ZEHİRLİ SIVI İÇEREN KATILAR, B.B.B."},
    "11 03 02*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "11 05 03*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "11 05 04*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "12 01 06*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "12 01 07*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "12 01 08*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "12 01 09*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "12 01 10*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "12 01 12*": {"un_no": "1223", "sinif": "3", "pg": "III", "sevkiyat_adi": "KEROSEN"},
    "12 01 14*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "12 01 16*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "12 01 18*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "12 01 19*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "12 01 20*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "12 03 01*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "12 03 02*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "13 01 01*": {"un_no": "2315", "sinif": "9", "pg": "II", "sevkiyat_adi": "POLİKLORİNLENMİŞ  BİFENİLLER, SIVI"},
    "13 01 04*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 01 05*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 01 09*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 01 10*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 01 11*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 01 12*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 01 13*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 02 04*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 02 05*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 02 06*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 02 07*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 02 08*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 03 01*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 03 06*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 03 07*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 03 08*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 03 09*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 03 10*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 04 01*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 04 02*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 04 03*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 05 01*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "13 05 02*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "13 05 03*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "13 05 06*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 05 07*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 05 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "13 07 01*": {"un_no": "1202", "sinif": "3", "pg": "III", "sevkiyat_adi": "GAZ YAĞI veya DİZEL YAKIT  veya ISITMA YAĞI, HAFİF  (parlama noktası 60 °C'den fazla  olmayan)"},
    "13 07 02*": {"un_no": "1203", "sinif": "3", "pg": "II", "sevkiyat_adi": "BENZİN veya GAZOLİN veya  PETROL"},
    "13 07 03*": {"un_no": "1993", "sinif": "3", "pg": "II", "sevkiyat_adi": "ALEVLENEBİLİR SIVI, B.B.B (50  °C'de buhar basıncı 110 kPa’dan daha  yüksek olan)"},
    "13 08 01*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "13 08 02*": {"un_no": "1202", "sinif": "3", "pg": "III", "sevkiyat_adi": "GAZ YAĞI veya DİZEL YAKIT  veya ISITMA YAĞI, HAFİF  (parlama noktası 60 °C'den fazla  olmayan)"},
    "13 08 99*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "14 06 01*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "14 06 02*": {"un_no": "3151", "sinif": "9", "pg": "II", "sevkiyat_adi": "POLİHALOJENLENMİŞ  BİFENİLLER, SIVI veya  HALOJENLENMİŞ  MONOMETİLDİFENİLMETANLAR, SIVI veya POLİHALOJENLENMİŞ  TERFENİLLER, SIVI"},
    "14 06 03*": {"un_no": "1993", "sinif": "3", "pg": "II", "sevkiyat_adi": "ALEVLENEBİLİR SIVI, B.B.B (50  °C'de buhar basıncı 110 kPa’dan daha  yüksek olan)"},
    "14 06 04*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "14 06 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "15 01 10*": {"un_no": "3509", "sinif": "9", "pg": "-", "sevkiyat_adi": "AMBALAJLAR, ISKARTA, BOŞ, TEMİZLENMEMİŞ"},
    "15 01 11*": {"un_no": "1950", "sinif": "2", "pg": "", "sevkiyat_adi": "AEROSOLLER, asfiksant"},
    "15 02 02*": {"un_no": "1373", "sinif": "4.2", "pg": "III", "sevkiyat_adi": "LİFLER veya KUMAŞLAR, HAYVANSAL veya BİTKİSEL veya  SENTETİK, B.B.B. yağlı"},
    "16 01 04*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "16 01 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "16 01 08*": {"un_no": "3506", "sinif": "8", "pg": "III", "sevkiyat_adi": "CİVA, ÜRETİLMİŞ NESNELER İÇİNDE"},
    "16 01 09*": {"un_no": "3548", "sinif": "9", "pg": "III", "sevkiyat_adi": "NESNELER, MUHTELİF TEHLİKELİ MALLAR İÇEREN, B.B.B."},
    "16 01 10*": {"un_no": "3268", "sinif": "9", "pg": "III", "sevkiyat_adi": "EMNİYET CİHAZLARI, elektrikle  çalışan"},
    "16 01 11*": {"un_no": "3363", "sinif": "9", "pg": "III", "sevkiyat_adi": "NESNELER İÇİNDE TEHLİKELİ  MALLAR veya MAKİNE İÇİNDE  TEHLİKELİ MALLAR ya da  APARAT İÇİNDE TEHLİKELİ  MALLAR"},
    "16 01 13*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "16 01 14*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "16 01 21*": {"un_no": "3548", "sinif": "9", "pg": "III", "sevkiyat_adi": "NESNELER, MUHTELİF TEHLİKELİ MALLAR İÇEREN, B.B.B."},
    "16 02 09*": {"un_no": "3432", "sinif": "9", "pg": "II", "sevkiyat_adi": "POLİKLORLU BİFENİLLER, KATI"},
    "16 02 10*": {"un_no": "3548", "sinif": "9", "pg": "III", "sevkiyat_adi": "NESNELER, MUHTELİF TEHLİKELİ MALLAR İÇEREN, B.B.B."},
    "16 02 11*": {"un_no": "3548", "sinif": "9", "pg": "III", "sevkiyat_adi": "NESNELER, MUHTELİF TEHLİKELİ MALLAR İÇEREN, B.B.B."},
    "16 02 12*": {"un_no": "3548", "sinif": "9", "pg": "III", "sevkiyat_adi": "NESNELER, MUHTELİF TEHLİKELİ MALLAR İÇEREN, B.B.B."},
    "16 02 13*": {"un_no": "3548", "sinif": "9", "pg": "III", "sevkiyat_adi": "NESNELER, MUHTELİF TEHLİKELİ MALLAR İÇEREN, B.B.B."},
    "16 02 15*": {"un_no": "3548", "sinif": "9", "pg": "III", "sevkiyat_adi": "NESNELER, MUHTELİF TEHLİKELİ MALLAR İÇEREN, B.B.B."},
    "16 03 03*": {"un_no": "3178", "sinif": "4.1", "pg": "III", "sevkiyat_adi": "ALEVLENEBİLİR KATI, İNORGANİK, B.B.B."},
    "16 03 05*": {"un_no": "3263", "sinif": "8", "pg": "III", "sevkiyat_adi": "AŞINDIRICI KATI, BAZİK, ORGANİK, B.B.B."},
    "16 03 07*": {"un_no": "2809", "sinif": "8", "pg": "III", "sevkiyat_adi": "CIVA"},
    "16 04 01*": {"un_no": "0353", "sinif": "1", "pg": "III", "sevkiyat_adi": "NESNELER, PATLAYICI, B.B.B."},
    "16 04 02*": {"un_no": "0353", "sinif": "1", "pg": "III", "sevkiyat_adi": "NESNELER, PATLAYICI, B.B.B."},
    "16 04 03*": {"un_no": "0353", "sinif": "1", "pg": "III", "sevkiyat_adi": "NESNELER, PATLAYICI, B.B.B."},
    "16 05 04*": {"un_no": "3538", "sinif": "2", "pg": "III", "sevkiyat_adi": "NESNELER, ALEVLENEBİLİR OLMAYAN, ZEHİRLİ OLMAYAN  GAZ İÇEREN, B.B.B."},
    "16 05 06*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "16 05 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "16 05 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "16 06 01*": {"un_no": "2794", "sinif": "8", "pg": "-", "sevkiyat_adi": "AKÜLER, SULU, ASİT  DOLDURULMUŞ, elektrik depolama"},
    "16 06 02*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "16 06 03*": {"un_no": "3506", "sinif": "8", "pg": "III", "sevkiyat_adi": "CİVA, ÜRETİLMİŞ NESNELER İÇİNDE"},
    "16 06 06*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "16 07 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "16 07 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "16 08 02*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "16 08 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "16 08 06*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "16 08 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "16 09 01*": {"un_no": "1482", "sinif": "5.1", "pg": "III", "sevkiyat_adi": "PERMANGANATLAR, İNORGANİK, B.B.B."},
    "16 09 02*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "16 09 03*": {"un_no": "2984", "sinif": "5.1", "pg": "III", "sevkiyat_adi": "HİDROJEN PEROKSİT, SULU  ÇÖZELTİ hidrojen peroksit oranı  %8'den fazla, ancak %20'den az  (gerektiği gibi stabilize)"},
    "16 09 04*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "16 10 01*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "16 10 03*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "16 11 01*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "16 11 03*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "16 11 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "17 01 06*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "17 02 04*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "17 03 01*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "17 03 03*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "17 04 09*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "17 04 10*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "17 05 03*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "17 05 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "17 05 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "17 06 01*": {"un_no": "2590", "sinif": "9", "pg": "III", "sevkiyat_adi": "ASBEST, KRİZOTİL"},
    "17 06 03*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "17 06 05*": {"un_no": "2590", "sinif": "9", "pg": "III", "sevkiyat_adi": "ASBEST, KRİZOTİL"},
    "17 08 01*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "17 09 01*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "17 09 02*": {"un_no": "3432", "sinif": "9", "pg": "II", "sevkiyat_adi": "POLİKLORLU BİFENİLLER, KATI"},
    "17 09 03*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "18 01 03*": {"un_no": "3291", "sinif": "6.2", "pg": "", "sevkiyat_adi": "KLİNİK ATIK, TANIMLANMAMIŞ, B.B.B. veya  (BİYOLOJİK) TIBBİ ATIK, B.B.B. veya DÜZENLENMİŞ TIBBİ ATIK, B.B.B."},
    "18 01 06*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "18 01 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "18 01 10*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "18 02 02*": {"un_no": "3291", "sinif": "6.2", "pg": "", "sevkiyat_adi": "KLİNİK ATIK, TANIMLANMAMIŞ, B.B.B. veya  (BİYOLOJİK) TIBBİ ATIK, B.B.B. veya DÜZENLENMİŞ TIBBİ ATIK, B.B.B."},
    "18 02 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "18 02 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 01 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 01 06*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 01 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 01 10*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 01 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 01 13*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 01 15*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 01 17*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 02 04*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 02 05*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "19 02 07*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "19 02 08*": {"un_no": "1993", "sinif": "3", "pg": "II", "sevkiyat_adi": "ALEVLENEBİLİR SIVI, B.B.B (50  °C'de buhar basıncı 110 kPa’dan daha  yüksek olan)"},
    "19 02 09*": {"un_no": "1325", "sinif": "4.1", "pg": "III", "sevkiyat_adi": "ALEVLENEBİLİR KATI, ORGANİK, B.B.B."},
    "19 02 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 03 04*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 03 06*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 03 08*": {"un_no": "2025", "sinif": "6.1", "pg": "III", "sevkiyat_adi": "CIVA BİLEŞİĞİ, KATI, B.B.B."},
    "19 04 02*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 04 03*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 07 02*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "19 08 06*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 08 07*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "19 08 08*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 08 10*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "19 08 11*": {"un_no": "1325", "sinif": "4.1", "pg": "III", "sevkiyat_adi": "ALEVLENEBİLİR KATI, ORGANİK, B.B.B."},
    "19 08 13*": {"un_no": "1325", "sinif": "4.1", "pg": "III", "sevkiyat_adi": "ALEVLENEBİLİR KATI, ORGANİK, B.B.B."},
    "19 10 03*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 10 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 11 01*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 11 02*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 11 03*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "19 11 04*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 11 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 11 07*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 12 06*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 12 11*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 13 01*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 13 03*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 13 05*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "19 13 07*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "20 01 13*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "20 01 14*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "20 01 15*": {"un_no": "3082", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, SIVI, B.B.B."},
    "20 01 17*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "20 01 19*": {"un_no": "2588", "sinif": "6.1", "pg": "III", "sevkiyat_adi": "PESTİSİT, KATI, ZEHİRLİ, B.B.B."},
    "20 01 21*": {"un_no": "3506", "sinif": "8", "pg": "III", "sevkiyat_adi": "CİVA, ÜRETİLMİŞ NESNELER İÇİNDE"},
    "20 01 23*": {"un_no": "3548", "sinif": "9", "pg": "III", "sevkiyat_adi": "NESNELER, MUHTELİF TEHLİKELİ MALLAR İÇEREN, B.B.B."},
    "20 01 26*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "20 01 27*": {"un_no": "1263", "sinif": "3", "pg": "II", "sevkiyat_adi": "BOYA (boya, vernik, emaye, renklendirici, lake, cila, parlatıcı, sıvı  dolgu ve sıvı vernik bazı dâhil) veya  BOYA İLE İLGİLİ MALZEME  (boya inceltici veya azaltıcı bileşiği  dâhil) (50 °C'de buhar basıncı 110  kPa’dan daha yüksek olan)"},
    "20 01 29*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "20 01 31*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "20 01 33*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
    "20 01 35*": {"un_no": "3548", "sinif": "9", "pg": "III", "sevkiyat_adi": "NESNELER, MUHTELİF TEHLİKELİ MALLAR İÇEREN, B.B.B."},
    "20 01 37*": {"un_no": "3077", "sinif": "9", "pg": "III", "sevkiyat_adi": "ÇEVREYE ZARARLI MADDE, KATI, B.B.B."},
}
